In [9]:
import pandas as pd
import numpy as np
df =pd.DataFrame({
    "name":["Alice","Bob","Charlie","David","rohit","agastya","amar","joy"],
     "age":[25,30,35,40,50,21,43,45],
     "city":["New York","Los Angeles","Chicago","Houston","hongkong","delhi","mumbai","kolkata"],
     "sal":[50000,60000,70000,80000,30000,32000,45000,870000]
})



for i in range(len(df)):
    df.loc[i,"sal"]=df.loc[i,"sal"]*1.0


df

      name  age         city     sal
0    Alice   25     New York   50000
1      Bob   30  Los Angeles   60000
2  Charlie   35      Chicago   70000
3    David   40      Houston   80000
4    rohit   50     hongkong   30000
5  agastya   21        delhi   32000
6     amar   43       mumbai   45000
7      joy   45      kolkata  870000

In [10]:
df["sal"]=df["sal"]*1.0
df

      name  age         city       sal
0    Alice   25     New York   50000.0
1      Bob   30  Los Angeles   60000.0
2  Charlie   35      Chicago   70000.0
3    David   40      Houston   80000.0
4    rohit   50     hongkong   30000.0
5  agastya   21        delhi   32000.0
6     amar   43       mumbai   45000.0
7      joy   45      kolkata  870000.0

In [11]:
df.loc[df["sal"]>50000,"age"]-=5
df

      name  age         city       sal
0    Alice   25     New York   50000.0
1      Bob   25  Los Angeles   60000.0
2  Charlie   30      Chicago   70000.0
3    David   35      Houston   80000.0
4    rohit   50     hongkong   30000.0
5  agastya   21        delhi   32000.0
6     amar   43       mumbai   45000.0
7      joy   40      kolkata  870000.0

In [12]:
data={
    "players":["virat","Rohit","sehwag","dhoni","virat","Rohit","virat","dhoni"],
    "matches":[25,123,89,15,108,170,111,20],
    "runs":[154,200,123,257,309,198,171,54],
    "Balls":[50,100,120,120,150,80,120,100]
}
df=pd.DataFrame(data)
df
### GroupBy
grp=df.groupby("players" )["runs"].sum()
grp

players
Rohit     398
dhoni     311
sehwag    123
virat     634
Name: runs, dtype: int64

In [13]:
### Aggregation
summ=df.groupby("players").agg(
    Total_runs=("runs", "sum"),
    Average_runs=("runs", "mean"),
    Matches_played=("matches","sum"),
    Highest_score=("runs","max"),
    Lowest_score=("runs","min"),
    Totals_balls=("Balls","sum")
).reset_index()

summ

,players,Total_runs,Average_runs,Matches_played,Highest_score,Lowest_score,Totals_balls
0,Rohit,398,199.000000,293,200,198,180
1,dhoni,311,155.500000,35,257,54,220
2,sehwag,123,123.000000,89,123,123,120
3,virat,634,211.333333,244,309,154,320

In [14]:
summ=df.groupby("players").agg(
    Total_runs=("runs", "sum"),
    Average_runs=("runs", "mean"),
    Matches_played=("matches","sum"),
    Highest_score=("runs","max"),
    Lowest_score=("runs","min"),
    Totals_balls=("Balls","sum"),
    Fifties=("runs",lambda x:((x>=50) & (x<100)).sum())
).reset_index()
summ

,players,Total_runs,Average_runs,Matches_played,Highest_score,Lowest_score,Totals_balls,Fifties
0,Rohit,398,199.000000,293,200,198,180,0
1,dhoni,311,155.500000,35,257,54,220,1
2,sehwag,123,123.000000,89,123,123,120,0
3,virat,634,211.333333,244,309,154,320,0