In [4]:
import pandas as pd

df = pd.DataFrame({
    "CustomerName": [
        "Priyvrat", "Rahul Sharma", "priya patel", "AMIT KUMAR",
        "neha gupta", "Vikas Jain", "priya patel", "sneha reddy",
        "rahul sharma ", "Pooja Mehta", None, "Priyvrat",
        "Arjun Reddy", "Kiran Rao", "Meena Kumari", "Suresh Babu",
        "Anita Singh", "Rahul Sharma", "Priya Patel", "Deepak Verma"
    ],

    "OrderDate": [
        "2023-08-25", "2023-01-15", "2023/02/20", "2023-03-10",
        "20-04-2025", "2023-05-25", "2023-06-30", "2023-07-15",
        "2023-08-20", "20-09-2010", None, "2023-08-25",
        "2023-09-01", "2023/10/05", "2023-11-12", "12-12-2023",
        "2024-01-10", "2023-01-15", "2023-02-20", "2024-02-25"
    ],

    "ProductName": [
        "Mouse", "Laptop", "Mobile", "Keyboard",
        "Headphones", "Mouse", "Mouse", "Printer",
        "Monitor", "Keyboard", "Mouse", "Mouse",
        "Laptop", "Mouse", "Mobile", "Keyboard",
        "Headphones", "Laptop", "Mouse", "Monitor"
    ],

    "Quantity": [
        "2", "1", "2", "koko",
        "1", "-3", "2", "1",
        "1", "2", "200", "2",
        "3", "-1", "2", "1",
        "2", "1", "2", "3"
    ],

    "Price": [
        20000, 50000, 20000, 1500,
        3000, 800, 800, 5000,
        10000, 1500, 800, 20000,
        50000, 2000, 20000, 1500,
        3000, 50000, 20000, 10000
    ],

    "City": [
        "Lucknow", "Mumbai", "Delhi", "Chicago",
        "Kolkata", "Hongkong", "Delhi", "Mumbai",
        "Kolkata", "Delhi", "Pune", "Lucknow",
        "Hyderabad", "Bangalore", "Chennai", "Delhi",
        "Mumbai", "Mumbai", "Delhi", "Pune"
    ],

    "DeliveryDate": [
        "2023-08-25", "2023-01-20", "2023/02/25", "2023-03-15",
        "25-04-2025", "2023-05-30", "2023-07-05", "2023-07-20",
        "2023-08-25", "2023-09-20", "2023-08-25", "2023-08-25",
        "2023-09-05", "2023/10/10", "2023-11-20", "15-12-2023",
        "2024-01-15", "2023-01-18", "2023-02-22", "2024-03-01"
    ]
})
df

,CustomerName,OrderDate,ProductName,Quantity,Price,City,DeliveryDate
0,Priyvrat,2023-08-25,Mouse,2,20000,Lucknow,2023-08-25
1,Rahul Sharma,2023-01-15,Laptop,1,50000,Mumbai,2023-01-20
2,priya patel,2023/02/20,Mobile,2,20000,Delhi,2023/02/25
3,AMIT KUMAR,2023-03-10,Keyboard,koko,1500,Chicago,2023-03-15
4,neha gupta,20-04-2025,Headphones,1,3000,Kolkata,25-04-2025
5,Vikas Jain,2023-05-25,Mouse,-3,800,Hongkong,2023-05-30
6,priya patel,2023-06-30,Mouse,2,800,Delhi,2023-07-05
7,sneha reddy,2023-07-15,Printer,1,5000,Mumbai,2023-07-20
8,rahul sharma,2023-08-20,Monitor,1,10000,Kolkata,2023-08-25
9,Pooja Mehta,20-09-2010,Keyboard,2,1500,Delhi,2023-09-20
10,NaN,NaN,Mouse,200,800,Pune,2023-08-25
11,Priyvrat,2023-08-25,Mouse,2,20000,Lucknow,2023-08-25
12,Arjun Reddy,2023-09-01,Laptop,3,50000,Hyderabad,2023-09-05
13,Kiran Rao,2023/10/05,Mouse,-1,2000,Bangalore,2023/10/10
14,Meena Kumari,2023-11-12,Mobile,2,20000,Chennai,2023-11-20
15,Suresh Babu,12-12-2023,Keyboard,1,1500,Delhi,15-12-2023
16,Anita Singh,2024-01-10,Headphones,2,3000,Mumbai,2024-01-15
17,Rahul Sharma,2023-01-15,Laptop,1,50000,Mumbai,2023-01-18
18,Priya Patel,2023-02-20,Mouse,2,20000,Delhi,2023-02-22
19,Deepak Verma,2024-02-25,Monitor,3,10000,Pune,2024-03-01

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerName  19 non-null     str
 1   OrderDate     19 non-null     str
 2   ProductName   20 non-null     str
 3   Quantity      20 non-null     str
 4   Price         20 non-null     int64
 5   City          20 non-null     str
 6   DeliveryDate  20 non-null     str
dtypes: int64(1), str(6)
memory usage: 1.2 KB

In [6]:
df.isna().sum()

CustomerName    1
OrderDate       1
ProductName     0
Quantity        0
Price           0
City            0
DeliveryDate    0
dtype: int64

In [7]:
df.describe()

              Price
count     20.000000
mean   14495.000000
std    17096.582453
min      800.000000
25%     1500.000000
50%     7500.000000
75%    20000.000000
max    50000.000000

In [8]:
df.dtypes

CustomerName      str
OrderDate         str
ProductName       str
Quantity          str
Price           int64
City              str
DeliveryDate      str
dtype: object

In [9]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11     True
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
dtype: bool

In [10]:
df.duplicated().sum()

np.int64(1)

In [11]:
df.dropna(axis=1)

   ProductName Quantity  Price       City DeliveryDate
0        Mouse        2  20000    Lucknow   2023-08-25
1       Laptop        1  50000     Mumbai   2023-01-20
2       Mobile        2  20000      Delhi   2023/02/25
3     Keyboard     koko   1500    Chicago   2023-03-15
4   Headphones        1   3000    Kolkata   25-04-2025
5        Mouse       -3    800   Hongkong   2023-05-30
6        Mouse        2    800      Delhi   2023-07-05
7      Printer        1   5000     Mumbai   2023-07-20
8      Monitor        1  10000    Kolkata   2023-08-25
9     Keyboard        2   1500      Delhi   2023-09-20
10       Mouse      200    800       Pune   2023-08-25
11       Mouse        2  20000    Lucknow   2023-08-25
12      Laptop        3  50000  Hyderabad   2023-09-05
13       Mouse       -1   2000  Bangalore   2023/10/10
14      Mobile        2  20000    Chennai   2023-11-20
15    Keyboard        1   1500      Delhi   15-12-2023
16  Headphones        2   3000     Mumbai   2024-01-15
17      Laptop        1  50000     Mumbai   2023-01-18
18       Mouse        2  20000      Delhi   2023-02-22
19     Monitor        3  10000       Pune   2024-03-01

In [12]:
df.dropna(axis=0)

,CustomerName,OrderDate,ProductName,Quantity,Price,City,DeliveryDate
0,Priyvrat,2023-08-25,Mouse,2,20000,Lucknow,2023-08-25
1,Rahul Sharma,2023-01-15,Laptop,1,50000,Mumbai,2023-01-20
2,priya patel,2023/02/20,Mobile,2,20000,Delhi,2023/02/25
3,AMIT KUMAR,2023-03-10,Keyboard,koko,1500,Chicago,2023-03-15
4,neha gupta,20-04-2025,Headphones,1,3000,Kolkata,25-04-2025
5,Vikas Jain,2023-05-25,Mouse,-3,800,Hongkong,2023-05-30
6,priya patel,2023-06-30,Mouse,2,800,Delhi,2023-07-05
7,sneha reddy,2023-07-15,Printer,1,5000,Mumbai,2023-07-20
8,rahul sharma,2023-08-20,Monitor,1,10000,Kolkata,2023-08-25
9,Pooja Mehta,20-09-2010,Keyboard,2,1500,Delhi,2023-09-20
11,Priyvrat,2023-08-25,Mouse,2,20000,Lucknow,2023-08-25
12,Arjun Reddy,2023-09-01,Laptop,3,50000,Hyderabad,2023-09-05
13,Kiran Rao,2023/10/05,Mouse,-1,2000,Bangalore,2023/10/10
14,Meena Kumari,2023-11-12,Mobile,2,20000,Chennai,2023-11-20
15,Suresh Babu,12-12-2023,Keyboard,1,1500,Delhi,15-12-2023
16,Anita Singh,2024-01-10,Headphones,2,3000,Mumbai,2024-01-15
17,Rahul Sharma,2023-01-15,Laptop,1,50000,Mumbai,2023-01-18
18,Priya Patel,2023-02-20,Mouse,2,20000,Delhi,2023-02-22
19,Deepak Verma,2024-02-25,Monitor,3,10000,Pune,2024-03-01

In [13]:
df.dropna(inplace=True)
df

,CustomerName,OrderDate,ProductName,Quantity,Price,City,DeliveryDate
0,Priyvrat,2023-08-25,Mouse,2,20000,Lucknow,2023-08-25
1,Rahul Sharma,2023-01-15,Laptop,1,50000,Mumbai,2023-01-20
2,priya patel,2023/02/20,Mobile,2,20000,Delhi,2023/02/25
3,AMIT KUMAR,2023-03-10,Keyboard,koko,1500,Chicago,2023-03-15
4,neha gupta,20-04-2025,Headphones,1,3000,Kolkata,25-04-2025
5,Vikas Jain,2023-05-25,Mouse,-3,800,Hongkong,2023-05-30
6,priya patel,2023-06-30,Mouse,2,800,Delhi,2023-07-05
7,sneha reddy,2023-07-15,Printer,1,5000,Mumbai,2023-07-20
8,rahul sharma,2023-08-20,Monitor,1,10000,Kolkata,2023-08-25
9,Pooja Mehta,20-09-2010,Keyboard,2,1500,Delhi,2023-09-20
11,Priyvrat,2023-08-25,Mouse,2,20000,Lucknow,2023-08-25
12,Arjun Reddy,2023-09-01,Laptop,3,50000,Hyderabad,2023-09-05
13,Kiran Rao,2023/10/05,Mouse,-1,2000,Bangalore,2023/10/10
14,Meena Kumari,2023-11-12,Mobile,2,20000,Chennai,2023-11-20
15,Suresh Babu,12-12-2023,Keyboard,1,1500,Delhi,15-12-2023
16,Anita Singh,2024-01-10,Headphones,2,3000,Mumbai,2024-01-15
17,Rahul Sharma,2023-01-15,Laptop,1,50000,Mumbai,2023-01-18
18,Priya Patel,2023-02-20,Mouse,2,20000,Delhi,2023-02-22
19,Deepak Verma,2024-02-25,Monitor,3,10000,Pune,2024-03-01

In [14]:
df["CustomerName"]=df["CustomerName"].str.strip()
df

,CustomerName,OrderDate,ProductName,Quantity,Price,City,DeliveryDate
0,Priyvrat,2023-08-25,Mouse,2,20000,Lucknow,2023-08-25
1,Rahul Sharma,2023-01-15,Laptop,1,50000,Mumbai,2023-01-20
2,priya patel,2023/02/20,Mobile,2,20000,Delhi,2023/02/25
3,AMIT KUMAR,2023-03-10,Keyboard,koko,1500,Chicago,2023-03-15
4,neha gupta,20-04-2025,Headphones,1,3000,Kolkata,25-04-2025
5,Vikas Jain,2023-05-25,Mouse,-3,800,Hongkong,2023-05-30
6,priya patel,2023-06-30,Mouse,2,800,Delhi,2023-07-05
7,sneha reddy,2023-07-15,Printer,1,5000,Mumbai,2023-07-20
8,rahul sharma,2023-08-20,Monitor,1,10000,Kolkata,2023-08-25
9,Pooja Mehta,20-09-2010,Keyboard,2,1500,Delhi,2023-09-20
11,Priyvrat,2023-08-25,Mouse,2,20000,Lucknow,2023-08-25
12,Arjun Reddy,2023-09-01,Laptop,3,50000,Hyderabad,2023-09-05
13,Kiran Rao,2023/10/05,Mouse,-1,2000,Bangalore,2023/10/10
14,Meena Kumari,2023-11-12,Mobile,2,20000,Chennai,2023-11-20
15,Suresh Babu,12-12-2023,Keyboard,1,1500,Delhi,15-12-2023
16,Anita Singh,2024-01-10,Headphones,2,3000,Mumbai,2024-01-15
17,Rahul Sharma,2023-01-15,Laptop,1,50000,Mumbai,2023-01-18
18,Priya Patel,2023-02-20,Mouse,2,20000,Delhi,2023-02-22
19,Deepak Verma,2024-02-25,Monitor,3,10000,Pune,2024-03-01

In [15]:
df["CustomerName"]=df["CustomerName"].str.title()
df

,CustomerName,OrderDate,ProductName,Quantity,Price,City,DeliveryDate
0,Priyvrat,2023-08-25,Mouse,2,20000,Lucknow,2023-08-25
1,Rahul Sharma,2023-01-15,Laptop,1,50000,Mumbai,2023-01-20
2,Priya Patel,2023/02/20,Mobile,2,20000,Delhi,2023/02/25
3,Amit Kumar,2023-03-10,Keyboard,koko,1500,Chicago,2023-03-15
4,Neha Gupta,20-04-2025,Headphones,1,3000,Kolkata,25-04-2025
5,Vikas Jain,2023-05-25,Mouse,-3,800,Hongkong,2023-05-30
6,Priya Patel,2023-06-30,Mouse,2,800,Delhi,2023-07-05
7,Sneha Reddy,2023-07-15,Printer,1,5000,Mumbai,2023-07-20
8,Rahul Sharma,2023-08-20,Monitor,1,10000,Kolkata,2023-08-25
9,Pooja Mehta,20-09-2010,Keyboard,2,1500,Delhi,2023-09-20
11,Priyvrat,2023-08-25,Mouse,2,20000,Lucknow,2023-08-25
12,Arjun Reddy,2023-09-01,Laptop,3,50000,Hyderabad,2023-09-05
13,Kiran Rao,2023/10/05,Mouse,-1,2000,Bangalore,2023/10/10
14,Meena Kumari,2023-11-12,Mobile,2,20000,Chennai,2023-11-20
15,Suresh Babu,12-12-2023,Keyboard,1,1500,Delhi,15-12-2023
16,Anita Singh,2024-01-10,Headphones,2,3000,Mumbai,2024-01-15
17,Rahul Sharma,2023-01-15,Laptop,1,50000,Mumbai,2023-01-18
18,Priya Patel,2023-02-20,Mouse,2,20000,Delhi,2023-02-22
19,Deepak Verma,2024-02-25,Monitor,3,10000,Pune,2024-03-01

In [16]:
df["Quantity"]=pd.to_numeric(df["Quantity"],errors="coerce")
df

,CustomerName,OrderDate,ProductName,Quantity,Price,City,DeliveryDate
0,Priyvrat,2023-08-25,Mouse,2.0,20000,Lucknow,2023-08-25
1,Rahul Sharma,2023-01-15,Laptop,1.0,50000,Mumbai,2023-01-20
2,Priya Patel,2023/02/20,Mobile,2.0,20000,Delhi,2023/02/25
3,Amit Kumar,2023-03-10,Keyboard,NaN,1500,Chicago,2023-03-15
4,Neha Gupta,20-04-2025,Headphones,1.0,3000,Kolkata,25-04-2025
5,Vikas Jain,2023-05-25,Mouse,-3.0,800,Hongkong,2023-05-30
6,Priya Patel,2023-06-30,Mouse,2.0,800,Delhi,2023-07-05
7,Sneha Reddy,2023-07-15,Printer,1.0,5000,Mumbai,2023-07-20
8,Rahul Sharma,2023-08-20,Monitor,1.0,10000,Kolkata,2023-08-25
9,Pooja Mehta,20-09-2010,Keyboard,2.0,1500,Delhi,2023-09-20
11,Priyvrat,2023-08-25,Mouse,2.0,20000,Lucknow,2023-08-25
12,Arjun Reddy,2023-09-01,Laptop,3.0,50000,Hyderabad,2023-09-05
13,Kiran Rao,2023/10/05,Mouse,-1.0,2000,Bangalore,2023/10/10
14,Meena Kumari,2023-11-12,Mobile,2.0,20000,Chennai,2023-11-20
15,Suresh Babu,12-12-2023,Keyboard,1.0,1500,Delhi,15-12-2023
16,Anita Singh,2024-01-10,Headphones,2.0,3000,Mumbai,2024-01-15
17,Rahul Sharma,2023-01-15,Laptop,1.0,50000,Mumbai,2023-01-18
18,Priya Patel,2023-02-20,Mouse,2.0,20000,Delhi,2023-02-22
19,Deepak Verma,2024-02-25,Monitor,3.0,10000,Pune,2024-03-01

In [17]:
df["Quantity"]=df["Quantity"].fillna(0)
df["Quantity"]

0     2.0
1     1.0
2     2.0
3     0.0
4     1.0
5    -3.0
6     2.0
7     1.0
8     1.0
9     2.0
11    2.0
12    3.0
13   -1.0
14    2.0
15    1.0
16    2.0
17    1.0
18    2.0
19    3.0
Name: Quantity, dtype: float64

In [18]:
df["Quantity"]=df["Quantity"].astype("int64")
df["Quantity"]

0     2
1     1
2     2
3     0
4     1
5    -3
6     2
7     1
8     1
9     2
11    2
12    3
13   -1
14    2
15    1
16    2
17    1
18    2
19    3
Name: Quantity, dtype: int64

In [19]:
df[df["Quantity"]<0]

,CustomerName,OrderDate,ProductName,Quantity,Price,City,DeliveryDate
5,Vikas Jain,2023-05-25,Mouse,-3,800,Hongkong,2023-05-30
13,Kiran Rao,2023/10/05,Mouse,-1,2000,Bangalore,2023/10/10

In [20]:
df["Quantity"]=df["Quantity"].abs()
df["Quantity"]

0     2
1     1
2     2
3     0
4     1
5     3
6     2
7     1
8     1
9     2
11    2
12    3
13    1
14    2
15    1
16    2
17    1
18    2
19    3
Name: Quantity, dtype: int64

In [21]:
df["City"]=df["City"].replace({"Delhi" : "China"})
df["City"]

0       Lucknow
1        Mumbai
2         China
3       Chicago
4       Kolkata
5      Hongkong
6         China
7        Mumbai
8       Kolkata
9         China
11      Lucknow
12    Hyderabad
13    Bangalore
14      Chennai
15        China
16       Mumbai
17       Mumbai
18        China
19         Pune
Name: City, dtype: str

In [22]:
df["City"]=df["City"].replace({"Delhi" : "China","Kolkata":"Hyderabad"})
df["City"]

0       Lucknow
1        Mumbai
2         China
3       Chicago
4     Hyderabad
5      Hongkong
6         China
7        Mumbai
8     Hyderabad
9         China
11      Lucknow
12    Hyderabad
13    Bangalore
14      Chennai
15        China
16       Mumbai
17       Mumbai
18        China
19         Pune
Name: City, dtype: str

In [23]:
def parseDate(datestr):
    if pd.isna(datestr):
        return pd.NaT

    datestr = str(datestr).strip()

    formats = [
        '%Y-%m-%d',
        '%Y/%m/%d',
        '%d-%m-%Y',
        '%Y-%d-%m',
        '%d/%m/%Y'
    ]

    for fmt in formats:
        try:
            return pd.to_datetime(datestr, format=fmt)
        except:
            continue

    return pd.NaT