DATA TYPES

In [ ]:
import pandas as pd
import numpy as np
df=pd.DataFrame({
    "Name":["Rahul","Joy","Kumar","Mahi","Jhanvi","Shubham","Priya","Anit"],
    "Age":[25,np.nan,35,40,50,np.nan,43,45],
    "City":["mumbai","delhi","chicago","kolkata",np.nan,"hongkong","delhi","kolkata"],
    "Sal":[50000,60000,70000,80000,30000,32000,45000,87000],
    "Experience":[2,5,7,np.nan,15,1,8,np.nan],
    "Department":["IT","HR","Finance",np.nan,"HR","Finance","IT","HR"]
})
df#age & experience col shows values in float type because it's containing NaN values,so pandas does this
  #for non-numerical cols no changes

      Name   Age      City    Sal  Experience Department
0    Rahul  25.0    mumbai  50000         2.0         IT
1      Joy   NaN     delhi  60000         5.0         HR
2    Kumar  35.0   chicago  70000         7.0    Finance
3     Mahi  40.0   kolkata  80000         NaN        NaN
4   Jhanvi  50.0       NaN  30000        15.0         HR
5  Shubham   NaN  hongkong  32000         1.0    Finance
6    Priya  43.0     delhi  45000         8.0         IT
7     Anit  45.0   kolkata  87000         NaN         HR

CHECK DATA TYPES

In [4]:
df.dtypes

Name              str
Age           float64
City              str
Sal             int64
Experience    float64
Department        str
dtype: object

step 1: TO convert age col into int type we must ensure col doesn't contain NaN values

In [6]:
df["Age"].fillna(0).astype(int)

0    25
1     0
2    35
3    40
4    50
5     0
6    43
7    45
Name: Age, dtype: int64

step2: When we display age col we get float values cause we didn't change original data and now our type is still float

In [8]:
df["Age"]

0    25.0
1     NaN
2    35.0
3    40.0
4    50.0
5     NaN
6    43.0
7    45.0
Name: Age, dtype: float64

step3: TO permanently convert into int

In [ ]:
df["Age"]=df["Age"].fillna(0).astype(int)
df["Age"]#without this we won't get outpur

0    25
1     0
2    35
3    40
4    50
5     0
6    43
7    45
Name: Age, dtype: int64

In [11]:
df["Age"].dtype

dtype('int64')

step4: here u can say it changed our original dataset

In [12]:
df

      Name  Age      City    Sal  Experience Department
0    Rahul   25    mumbai  50000         2.0         IT
1      Joy    0     delhi  60000         5.0         HR
2    Kumar   35   chicago  70000         7.0    Finance
3     Mahi   40   kolkata  80000         NaN        NaN
4   Jhanvi   50       NaN  30000        15.0         HR
5  Shubham    0  hongkong  32000         1.0    Finance
6    Priya   43     delhi  45000         8.0         IT
7     Anit   45   kolkata  87000         NaN         HR

Example-2

In [13]:
df["Experience"]

0     2.0
1     5.0
2     7.0
3     NaN
4    15.0
5     1.0
6     8.0
7     NaN
Name: Experience, dtype: float64

In [14]:
df["Experience"].dtype

dtype('float64')

In [15]:
df["Experience"].fillna(0).astype(int)

0     2
1     5
2     7
3     0
4    15
5     1
6     8
7     0
Name: Experience, dtype: int64

In [16]:
df["Experience"]

0     2.0
1     5.0
2     7.0
3     NaN
4    15.0
5     1.0
6     8.0
7     NaN
Name: Experience, dtype: float64

In [17]:
df["Experience"].dtype

dtype('float64')

In [19]:
df["Experience"]=df["Experience"].fillna(0).astype(int)
df["Experience"]

0     2
1     5
2     7
3     0
4    15
5     1
6     8
7     0
Name: Experience, dtype: int64

In [20]:
df["Experience"]

0     2
1     5
2     7
3     0
4    15
5     1
6     8
7     0
Name: Experience, dtype: int64

In [21]:
df

      Name  Age      City    Sal  Experience Department
0    Rahul   25    mumbai  50000           2         IT
1      Joy    0     delhi  60000           5         HR
2    Kumar   35   chicago  70000           7    Finance
3     Mahi   40   kolkata  80000           0        NaN
4   Jhanvi   50       NaN  30000          15         HR
5  Shubham    0  hongkong  32000           1    Finance
6    Priya   43     delhi  45000           8         IT
7     Anit   45   kolkata  87000           0         HR

Converting int -----> float

In [22]:
df["Experience"]=df["Experience"].astype(float)
df["Experience"]

0     2.0
1     5.0
2     7.0
3     0.0
4    15.0
5     1.0
6     8.0
7     0.0
Name: Experience, dtype: float64

Converting int/float -------> string

In [23]:
df["Age"]=df["Age"].astype(str)
df["Age"]

0    25
1     0
2    35
3    40
4    50
5     0
6    43
7    45
Name: Age, dtype: str

In [ ]:
df["Age"]=df["Age"].astype(int)#converting back to int so original data does'nt effect
df["Age"]

0    25
1     0
2    35
3    40
4    50
5     0
6    43
7    45
Name: Age, dtype: int64

Number -------> boolean

EX-1 : checking the condition and storing boolean result by creating new column (changes original data)

In [28]:
df["flag"]=df["Age"]>30
df

      Name  Age      City    Sal  Experience Department   flag
0    Rahul   25    mumbai  50000         2.0         IT  False
1      Joy    0     delhi  60000         5.0         HR  False
2    Kumar   35   chicago  70000         7.0    Finance   True
3     Mahi   40   kolkata  80000         0.0        NaN   True
4   Jhanvi   50       NaN  30000        15.0         HR   True
5  Shubham    0  hongkong  32000         1.0    Finance  False
6    Priya   43     delhi  45000         8.0         IT   True
7     Anit   45   kolkata  87000         0.0         HR   True

In [29]:
df

      Name  Age      City    Sal  Experience Department   flag
0    Rahul   25    mumbai  50000         2.0         IT  False
1      Joy    0     delhi  60000         5.0         HR  False
2    Kumar   35   chicago  70000         7.0    Finance   True
3     Mahi   40   kolkata  80000         0.0        NaN   True
4   Jhanvi   50       NaN  30000        15.0         HR   True
5  Shubham    0  hongkong  32000         1.0    Finance  False
6    Priya   43     delhi  45000         8.0         IT   True
7     Anit   45   kolkata  87000         0.0         HR   True

EX-2 : Number ----> boolean (By Adding NEW COL..)
1. Add new column 
2. convert to  boolean using condition on new col

In [33]:
#df["Bonus"]=500 --> I'm not using this because all values will be 500 and this concept is called "BROADCASTING"
df["Bonus"]=df["Sal"]*500
df

      Name  Age      City    Sal  Experience Department   flag     Bonus
0    Rahul   25    mumbai  50000         2.0         IT  False  25000000
1      Joy    0     delhi  60000         5.0         HR  False  30000000
2    Kumar   35   chicago  70000         7.0    Finance   True  35000000
3     Mahi   40   kolkata  80000         0.0        NaN   True  40000000
4   Jhanvi   50       NaN  30000        15.0         HR   True  15000000
5  Shubham    0  hongkong  32000         1.0    Finance  False  16000000
6    Priya   43     delhi  45000         8.0         IT   True  22500000
7     Anit   45   kolkata  87000         0.0         HR   True  43500000

In [44]:
df["High-paid"]=df["Bonus"]>30000000
df

,Name,Age,City,Sal,Experience,Department,flag,Bonus,High-paid
0,Rahul,25,mumbai,50000,2.0,IT,False,25000000,False
1,Joy,0,delhi,60000,5.0,HR,False,30000000,False
2,Kumar,35,chicago,70000,7.0,Finance,True,35000000,True
3,Mahi,40,kolkata,80000,0.0,NaN,True,40000000,True
4,Jhanvi,50,NaN,30000,15.0,HR,True,15000000,False
5,Shubham,0,hongkong,32000,1.0,Finance,False,16000000,False
6,Priya,43,delhi,45000,8.0,IT,True,22500000,False
7,Anit,45,kolkata,87000,0.0,HR,True,43500000,True

In [45]:
df["High-paid"].dtype

dtype('bool')

In [37]:
df

,Name,Age,City,Sal,Experience,Department,flag,Bonus,High-paid
0,Rahul,25,mumbai,50000,2.0,IT,False,25000000,False
1,Joy,0,delhi,60000,5.0,HR,False,30000000,False
2,Kumar,35,chicago,70000,7.0,Finance,True,35000000,True
3,Mahi,40,kolkata,80000,0.0,NaN,True,40000000,True
4,Jhanvi,50,NaN,30000,15.0,HR,True,15000000,False
5,Shubham,0,hongkong,32000,1.0,Finance,False,16000000,False
6,Priya,43,delhi,45000,8.0,IT,True,22500000,False
7,Anit,45,kolkata,87000,0.0,HR,True,43500000,True

EX-3: Number ----> boolean (Temporary change)

In [40]:
df["Sal"]<50000

0    False
1    False
2    False
3    False
4     True
5     True
6     True
7    False
Name: Sal, dtype: bool

In [46]:
df

,Name,Age,City,Sal,Experience,Department,flag,Bonus,High-paid
0,Rahul,25,mumbai,50000,2.0,IT,False,25000000,False
1,Joy,0,delhi,60000,5.0,HR,False,30000000,False
2,Kumar,35,chicago,70000,7.0,Finance,True,35000000,True
3,Mahi,40,kolkata,80000,0.0,NaN,True,40000000,True
4,Jhanvi,50,NaN,30000,15.0,HR,True,15000000,False
5,Shubham,0,hongkong,32000,1.0,Finance,False,16000000,False
6,Priya,43,delhi,45000,8.0,IT,True,22500000,False
7,Anit,45,kolkata,87000,0.0,HR,True,43500000,True

Converting datatypes Of Categorical Cols

In [ ]:
df[["City","Department","Name"]]#Ensure to use double square brackets in case of multiple cols

       City Department     Name
0    mumbai         IT    Rahul
1     delhi         HR      Joy
2   chicago    Finance    Kumar
3   kolkata        NaN     Mahi
4       NaN         HR   Jhanvi
5  hongkong    Finance  Shubham
6     delhi         IT    Priya
7   kolkata         HR     Anit

Temporary conversion

In [ ]:
df["City"].astype("category").cat.codes #1.  df["City"] is selecting city col
                                        #2.  .astype("category") here pandas is treating text data as categories not as plain text
                                        #3.  .cat.codes here pandas convert data into numbers alphabetical wise ex-c,d,h,k,m is order so numbers 0,1,2,3,4
                                        #4.  NaN becomes -1 cuz pandas consider missing values as -1

0    4
1    1
2    0
3    3
4   -1
5    2
6    1
7    3
dtype: int8

In [50]:
df["City"]

0      mumbai
1       delhi
2     chicago
3     kolkata
4         NaN
5    hongkong
6       delhi
7     kolkata
Name: City, dtype: str

Permanent Change

In [52]:
df["City"]=df["City"].astype("category").cat.codes
df["City"]

0    5
1    2
2    1
3    4
4    0
5    3
6    2
7    4
Name: City, dtype: int8

In [53]:
df

,Name,Age,City,Sal,Experience,Department,flag,Bonus,High-paid
0,Rahul,25,5,50000,2.0,IT,False,25000000,False
1,Joy,0,2,60000,5.0,HR,False,30000000,False
2,Kumar,35,1,70000,7.0,Finance,True,35000000,True
3,Mahi,40,4,80000,0.0,NaN,True,40000000,True
4,Jhanvi,50,0,30000,15.0,HR,True,15000000,False
5,Shubham,0,3,32000,1.0,Finance,False,16000000,False
6,Priya,43,2,45000,8.0,IT,True,22500000,False
7,Anit,45,4,87000,0.0,HR,True,43500000,True

NAME COL - SEE CAREFULLY

1. Temporary

In [55]:
df["Name"]

0      Rahul
1        Joy
2      Kumar
3       Mahi
4     Jhanvi
5    Shubham
6      Priya
7       Anit
Name: Name, dtype: str

In [ ]:
df["Name"].astype("category").cat.codes #order a,j,k,m,p,r,s = 0,1,2,3,4,5,6,7 (first jh then jo , o comes after h)

0    6
1    2
2    3
3    4
4    1
5    7
6    5
7    0
dtype: int8

In [57]:
df["Name"]

0      Rahul
1        Joy
2      Kumar
3       Mahi
4     Jhanvi
5    Shubham
6      Priya
7       Anit
Name: Name, dtype: str

Permanent

In [59]:
df["Name"]=df["Name"].astype("category").cat.codes
df["Name"]

0    6
1    2
2    3
3    4
4    1
5    7
6    5
7    0
Name: Name, dtype: int8

In [60]:
df["Name"]

0    6
1    2
2    3
3    4
4    1
5    7
6    5
7    0
Name: Name, dtype: int8

In [61]:
df

   Name  Age  City    Sal  Experience Department   flag     Bonus  High-paid
0     6   25     5  50000         2.0         IT  False  25000000      False
1     2    0     2  60000         5.0         HR  False  30000000      False
2     3   35     1  70000         7.0    Finance   True  35000000       True
3     4   40     4  80000         0.0        NaN   True  40000000       True
4     1   50     0  30000        15.0         HR   True  15000000      False
5     7    0     3  32000         1.0    Finance  False  16000000      False
6     5   43     2  45000         8.0         IT   True  22500000      False
7     0   45     4  87000         0.0         HR   True  43500000       True