In [4]:
import pandas as pd
import numpy as np
df=pd.DataFrame({
    "Name":["Rahul","Joy","Kumar","Mahi","Jhanvi","Shubham","Priya","Anit"],
    "Age":[25,np.nan,35,40,50,np.nan,43,45],
    "City":["mumbai","delhi","chicago","kolkata",np.nan,"hongkong","delhi","kolkata"],
    "Sal":[50000,60000,70000,80000,30000,32000,45000,87000],
    "Experience":[2,5,7,np.nan,15,1,8,np.nan],
    "Department":["IT","HR","Finance",np.nan,"HR","Finance","IT","HR"]
})
df

      Name   Age      City    Sal  Experience Department
0    Rahul  25.0    mumbai  50000         2.0         IT
1      Joy   NaN     delhi  60000         5.0         HR
2    Kumar  35.0   chicago  70000         7.0    Finance
3     Mahi  40.0   kolkata  80000         NaN        NaN
4   Jhanvi  50.0       NaN  30000        15.0         HR
5  Shubham   NaN  hongkong  32000         1.0    Finance
6    Priya  43.0     delhi  45000         8.0         IT
7     Anit  45.0   kolkata  87000         NaN         HR

TO FETCH FIRST 5 ROWS FROM DATA USE HEAD()

In [5]:
df.head()

     Name   Age     City    Sal  Experience Department
0   Rahul  25.0   mumbai  50000         2.0         IT
1     Joy   NaN    delhi  60000         5.0         HR
2   Kumar  35.0  chicago  70000         7.0    Finance
3    Mahi  40.0  kolkata  80000         NaN        NaN
4  Jhanvi  50.0      NaN  30000        15.0         HR

TO KNOW THE COUNT OF NON-NULL VALUES IN EACH COLUMN ALONG WITH THEIR DATATYPE USE INFO()

In [ ]:
df.info()#specifies count of not-null values in each col,&  datatypes of col

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        8 non-null      str
 1   Age         6 non-null      float64
 2   City        7 non-null      str
 3   Sal         8 non-null      int64
 4   Experience  6 non-null      float64
 5   Department  7 non-null      str
dtypes: float64(2), int64(1), str(3)
memory usage: 516.0 bytes

TO GET COUNT,MIN,MAX,STD FOR NUMERICAL VALUES(NUMERICAL SUMMARY) USE DESCRIBE()

In [7]:
df.describe()

             Age           Sal  Experience
count   6.000000      8.000000    6.000000
mean   39.666667  56750.000000    6.333333
std     8.755950  21224.985277    5.046451
min    25.000000  30000.000000    1.000000
25%    36.250000  41750.000000    2.750000
50%    41.500000  55000.000000    6.000000
75%    44.500000  72500.000000    7.750000
max    50.000000  87000.000000   15.000000

TO GET COUNT OF NON-NUMERICAL COLUMNS(CATEGORICAL SUMMARY) USE (INCLUDE="OBJECT") ALONG WITH DESCRIBE()

In [ ]:
df.describe(include="object")#here 1.count gives count of non-null values
                                    #2.unique gives count of unique values
                                    #3.top gives the value which is more repeated in the column(incase their are no repeated values it considers the first value from the column)
                                    #4.freq gives count of how many types the top value repeated

C:\Users\ctrkt\AppData\Local\Temp\ipykernel_4952\702825166.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

         Name   City Department
count       8      7          7
unique      8      5          3
top     Rahul  delhi         HR
freq        1      2          3

TO GET SUMMARY OF BOTH NUMERICAL AND CATEGORICAL USE STATISTICAL SUMMARY ,HERE WE USE (INCLUDE="ALL") ALONG WITH DESCRIBE()

In [9]:
df.describe(include="all")

         Name        Age   City           Sal  Experience Department
count       8   6.000000      7      8.000000    6.000000          7
unique      8        NaN      5           NaN         NaN          3
top     Rahul        NaN  delhi           NaN         NaN         HR
freq        1        NaN      2           NaN         NaN          3
mean      NaN  39.666667    NaN  56750.000000    6.333333        NaN
std       NaN   8.755950    NaN  21224.985277    5.046451        NaN
min       NaN  25.000000    NaN  30000.000000    1.000000        NaN
25%       NaN  36.250000    NaN  41750.000000    2.750000        NaN
50%       NaN  41.500000    NaN  55000.000000    6.000000        NaN
75%       NaN  44.500000    NaN  72500.000000    7.750000        NaN
max       NaN  50.000000    NaN  87000.000000   15.000000        NaN

TO CHECK MISSING VALUES USE ISNULL()
IF THEIR IS NAN VALUE IT RETURNS TRUE ELSE RETURNS FALSE

In [10]:
df.isnull()

    Name    Age   City    Sal  Experience  Department
0  False  False  False  False       False       False
1  False   True  False  False       False       False
2  False  False  False  False       False       False
3  False  False  False  False        True        True
4  False  False   True  False       False       False
5  False   True  False  False       False       False
6  False  False  False  False       False       False
7  False  False  False  False        True       False

TO GET COUNT OF MISSING VALUES

In [12]:
df.isnull().sum()#in isnull() we get true/false where true=1,false=0 then sum() adds these 0's & 1's and returns count of missing values (as result is int type pandas display dtype as int64)

Name          0
Age           2
City          1
Sal           0
Experience    2
Department    1
dtype: int64

TO REPLACE/CONVERT NAN VALUES IN ANY COLUMN USE FILLNA()

In [13]:
df.fillna(0)

      Name   Age      City    Sal  Experience Department
0    Rahul  25.0    mumbai  50000         2.0         IT
1      Joy   0.0     delhi  60000         5.0         HR
2    Kumar  35.0   chicago  70000         7.0    Finance
3     Mahi  40.0   kolkata  80000         0.0          0
4   Jhanvi  50.0         0  30000        15.0         HR
5  Shubham   0.0  hongkong  32000         1.0    Finance
6    Priya  43.0     delhi  45000         8.0         IT
7     Anit  45.0   kolkata  87000         0.0         HR

In [14]:
df.fillna(3)

      Name   Age      City    Sal  Experience Department
0    Rahul  25.0    mumbai  50000         2.0         IT
1      Joy   3.0     delhi  60000         5.0         HR
2    Kumar  35.0   chicago  70000         7.0    Finance
3     Mahi  40.0   kolkata  80000         3.0          3
4   Jhanvi  50.0         3  30000        15.0         HR
5  Shubham   3.0  hongkong  32000         1.0    Finance
6    Priya  43.0     delhi  45000         8.0         IT
7     Anit  45.0   kolkata  87000         3.0         HR